client/urls.py
from django.urls import path
from . import views

app_name = 'client'
urlpatterns=[

    path("", views.clients_list, name="clients_list"),
    path("<int:pk>/", views.clients_detail, name="clients_detail"),
    path("<int:pk>/delete/", views.clients_delete, name="clients_delete"),
    path("<int:pk>/edit/", views.clients_edit, name="clients_edit"),
    path("add/", views.clients_add, name="clients_add"),

    ]

crm/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('website/', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('facturation/', include('facturation.urls')),
    path('team/', include('team.urls')),
    path('todo/', include('todo.urls')),
    path('leads/', include('leads.urls')),
    path('client/', include('client.urls')),

]

client/models.py
from django.db import models
from django.contrib.auth.models import User
from team.models import Team


class Client(models.Model):
    team=models.ForeignKey(Team, related_name='teams', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering= ('name',)

    def __str__(self):
        return self.name

client/forms.py
from django import forms
from .models import Client


class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'description', )

client/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Client
from team.models import Team
from .forms import AddClientForm

@login_required
def clients_list(request):
    clients= Client.objects.filter(created_by=request.user)
    return render(request, 'clients_list.html', {'clients':clients})

@login_required
def clients_detail(request, pk):
    client=get_object_or_404(Client, created_by=request.user, pk=pk)
    return render(request, 'clients_detail.html', {'client':client})
@login_required
def clients_add(request):
    if request.method=='POST':
        form=AddClientForm(request.POST)
        if form.is_valid():
            team = Team.objects.filter(created_by = request.user).first()
            client=form.save(commit=False)
            client.created_by=request.user
            client.team = team
            client.save()
            messages.success(request, 'Un client a été ajouté')
            return redirect('client:clients_list')
    else:
        form= AddClientForm()
    return render(request, 'clients_add.html', {'form':form})

@login_required
def clients_delete(request, pk):
    client=get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()
    messages.success(request, 'vous avez supprimé le client')
    return redirect('client:clients_list')

@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    if request.method == 'POST':
        form = AddClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            messages.success(request, 'Les changements ont été effectués')
            return redirect('client:clients_list')
    else:
        form=AddClientForm(instance=client)
        return render(request, 'clients_edit.html', {'form': form})

client/templates/clients_add.html
{% extends 'base.html' %}

{% block content %}



<div class="py-6 px-6">

    <h1 class="text-xl"> Ajouter un client</h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Créer</button>
    </form>
</div>

{% endblock %}

client/templates/clients_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl"> {{ client.name}}</h1>


        {% if client.description %}
       <p><strong>Description</strong></p>
        <p class="mb-4"> {{client.description}} </p>
        {% endif %}

       <p><strong>Créé le</strong></p>
        <p class="mb-4"> {{client.created_at}} </p>

        <p><strong>Modifié le</strong></p>
        <p class="mb-4"> {{client.modified_at}} </p>

        <hr class="my-2">

        <a href="{% url 'client:clients_delete' client.id %} " class=" btn btn-danger">Supprimer</a>
        <a href="{% url 'client:clients_edit' pk=client.id %}" class="btn btn-success">Modifier</a>

        <hr class="my-2">
        <a href="{% url 'client:clients_list' %}" class=" btn">Retour</a>




    </div>

{% endblock%}

client/templates/clients_edit.html
{% extends 'base.html' %}

{% block content %}



<div class="py-6 px-6">

    <h1 class="text-xl"> Modifier </h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Modifier</button>
    </form>
</div>

{% endblock %}

client/templates/clients_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Liste des clients</h1>
        <a class="nav-link bg-success w-100 rounded text-center fs-6 mt-4" href="{% url 'client:clients_add' %}">
            <span>Ajouter un client</span>
        </a>
        {% if clients %}
            <div class="d-flex justify-content-between mt-4">
                <p class="py-2 px-2 bg-secondary text-center fs-6 font-semibold w-100">Nom</p>

            </div>
         {% for client in clients %}
            <div class="d-flex justify-content-between {% cycle 'bg-gray-100' 'bg-white' %}">
                <p class="py-2 px-2 w-full"><a href=" {% url 'client:clients_detail' client.id %} " >{{ client.name }}</a></p>
            </div>
        {% endfor %}
        {% else %}
        <p class="mt-4"> Il n y a pas de client dans la base de données ...</p>
        {% endif%}
    </div>
{% endblock %}