crm/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('website/', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('facturation/', include('facturation.urls')),
    path('team/', include('team.urls')),
    path('todo/', include('todo.urls')),
    path('leads/', include('leads.urls')),
    path('client/', include('client.urls')),

]

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'
urlpatterns=[

    path("", views.leads_list, name="leads_list"),
    path("<int:pk>/", views.leads_detail, name="leads_detail"),
    path('<int:pk>/delete/', views.leads_delete, name='leads_delete'),
    path("add_lead/", views.add_lead, name="add_lead"),
    path("<int:pk>/convert", views.convert_to_client, name="leads_convert"),
    path('<int:pk>/edit/', views.leads_edit, name="leads_edit"),

]

leads/models.py
from django.db import models
from django.contrib.auth.models import User
from team.models import Team

class Lead(models.Model):
    LOW = "faible"
    MEDIUM = "moyenne"
    HIGH = "forte"

    CHOICES_PRIORITY = (
        (LOW, "faible"),
        (MEDIUM, "moyenne"),
        (HIGH, "forte"),
    )

    NEW = 'nouveau'
    CONTACTED = 'contacté'
    WON = 'gagné'
    LOST = 'perdu'

    CHOICES_STATUS = (
        (NEW, 'nouveau'),
        (CONTACTED, 'contacté'),
        (WON, 'gagné'),
        (LOST, 'perdu'),
    )
    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client=models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering= ('name',)

    def __str__(self):
        return self.name

leads/forms.py
from django import forms
from .models import Lead


class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status')

leads/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from . forms import AddLeadForm
from .models import Lead
from team.models import Team
from client.models import Client


@login_required
def leads_list(request):
    leads= Lead.objects.filter(created_by=request.user, converted_to_client=False)
    return render(request, 'leads_list.html', {'leads':leads})


@login_required
def leads_detail(request, pk):
    lead=get_object_or_404(Lead, created_by=request.user, pk=pk)

    return render(request, 'leads_detail.html',{ 'lead':lead})



@login_required
def leads_delete(request, pk):
    lead=get_object_or_404(Lead, created_by=request.user, pk=pk)
    lead.delete()
    messages.success(request, 'vous avez supprimé le prospect')
    return redirect('leads:leads_list')

@login_required
def leads_edit(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    if request.method == 'POST':
        form = AddLeadForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            messages.success(request, 'Les changement ont été effectués')
            return redirect('leads:leads_list')
    else:
        form=AddLeadForm(instance=lead)
        return render(request, 'leads_edit.html', {'form': form})


@login_required
def add_lead(request):
    if request.method=='POST':
        team = Team.objects.filter(created_by=request.user).first()
        form=AddLeadForm(request.POST)
        if form.is_valid():
            lead=form.save(commit=False)
            lead.created_by=request.user
            lead.team = team
            lead.save()
            messages.success(request, 'Un prospect a été ajouté')
            return redirect('leads:leads_list')
    else:
        form= AddLeadForm()
    return render(request, 'add_lead.html', {'form':form})


@login_required
def convert_to_client(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    team = Team.objects.filter(created_by=request.user).first()
    if team:
        client = Client.objects.create(
            name=lead.name,
            email=lead.email,
            description=lead.description,
            created_by=request.user,
            team=team,
        )
        lead.converted_to_client = True
        lead.save()
        messages.success(request, 'Le prospect est converti en un client')
    else:
        messages.error(request, 'Vous devez avoir une équipe pour convertir un prospect en client')

    return redirect('leads:leads_list')

leads/templates/add_lead.html
{% extends 'base.html' %}

{% block content %}



<div class="py-6 px-6">

    <h1 class="text-xl"> Ajouter un prospect</h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Créer</button>
    </form>
</div>

{% endblock %}

leads/templates/leads_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl"> {{ lead.name}}</h1>


        {% if lead.description %}
       <p><strong>Nom</strong></p>
        <p class="mb-4"> {{lead.description}} </p>
        {% endif %}

       <p><strong>Priorité</strong></p>
        <p class="mb-4"> {{lead.get_priority_display}} </p>

       <p><strong>Statut</strong></p>
        <p class="mb-4"> {{lead.get_status_display}} </p>

       <p><strong>Crée le</strong></p>
        <p class="mb-4"> {{lead.created_at}} </p>

        <p><strong>Modifié le</strong></p>
        <p class="mb-4"> {{lead.modified_at}} </p>

        <hr class="my-2">
        <a href="{% url 'leads:leads_convert' lead.id %}" class=" btn btn-secondary">Convertir en client</a>
        <a href="{% url 'leads:leads_delete' lead.id %}" class=" btn btn-danger">Supprimer</a>
        <a href="{% url 'leads:leads_edit' lead.id %}" class=" btn btn-success">Modifier</a>
        <hr class="my-2">
        <a href="{% url 'leads:leads_list' %}" class=" btn">Retour</a>


        
        
    </div>

{% endblock%}

leads/templates/leads_edit.html
{% extends 'base.html' %}

{% block content %}



<div class="py-6 px-6">

    <h1 class="text-xl"> Modifier </h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Modifier</button>
    </form>
</div>

{% endblock %}

leads/templates/leads_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Liste des prospects</h1>
        <a class="nav-link bg-success w-100 rounded text-center fs-6 mt-4" href="{% url 'leads:add_lead' %}">
            <span>Ajouter un prospect</span>
        </a>
        {% if leads %}
            <div class="d-flex justify-content-between mt-4">
                <p class="py-2 px-2 bg-secondary text-center fs-6 font-semibold w-100">Nom</p>
                <p class="py-2 px-2 bg-secondary  text-center fs-6 font-semibold w-100">Priorité</p>
                <p class="py-2 px-2 bg-secondary   text-center fs-6 font-semibold w-100">Statut</p>
            </div>
         {% for lead in leads %}
            <div class="d-flex justify-content-between {% cycle 'bg-gray-100' 'bg-white' %}">
                <p class="py-2 px-2 w-full"><a href="{% url 'leads:leads_detail' lead.id %}">{{ lead.name }}</a></p>
                <p class="py-2 px-2 w-full">{{ lead.get_priority_display }}</p>
                <p class="py-2 px-2 w-full">{{ lead.get_status_display }}</p>
            </div>
        {% endfor %}
        {% else %}
        <p class="mt-4"> Il n y a pas de prospects dans la base de données ...</p>
        {% endif%}
    </div>
{% endblock %}