client/urls.py
from django.urls import path
from . import views

app_name = 'client'
urlpatterns=[

    path("", views.clients_list, name="clients_list"),
    path("<int:pk>/", views.clients_detail, name="clients_detail"),
    path("<int:pk>/delete/", views.clients_delete, name="clients_delete"),
    path("<int:pk>/edit/", views.clients_edit, name="clients_edit"),
    path("add/", views.clients_add, name="clients_add"),

    ]

crm/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('website/', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('facturation/', include('facturation.urls')),
    path('team/', include('team.urls')),
    path('todo/', include('todo.urls')),
    path('leads/', include('leads.urls')),
    path('client/', include('client.urls')),

]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns=[
    path("", views.dashboard, name="dashboard"),
]

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'
urlpatterns=[

    path("", views.leads_list, name="leads_list"),
    path("<int:pk>/", views.leads_detail, name="leads_detail"),
    path('<int:pk>/delete/', views.leads_delete, name='leads_delete'),
    path("add_lead/", views.add_lead, name="add_lead"),
    path("<int:pk>/convert", views.convert_to_client, name="leads_convert"),
    path('<int:pk>/edit/', views.leads_edit, name="leads_edit"),

]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns=[
    path("", views.todo_list, name="todo_list"),
]

website/urls.py
from django.urls import path
from . import views


app_name = 'website'
urlpatterns = [
    path("", views.site, name='site'),
    path("crm/",views.records, name='records'),
    path("factures/",views.factures, name='factures'),
    path("myaccount/", views.my_account, name="myaccount"),
    path("logout/",views.logout_user, name='logout'),
    path("register/",views.register_user, name='register'),
    path("record/<int:pk>",views.customer_record, name='record'),
    path("delete_record/<int:pk>",views.delete_record, name='delete_record'),
    path("add_record/",views.add_record, name='add_record'),
    path("update_record/<int:pk>",views.update_record, name='update_record'),


]

website/models.py
from django.db import models


class Record(models.Model):
    #team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    adress = models.CharField(max_length=150)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=20)

    def __str__(self):
        return(f"{self.first_name} {self.last_name}")

website/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Record

class SignUpForm(UserCreationForm):
    email=forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Adresse e-mail'}))
    first_name=forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Prénom'}))
    last_name=forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Nom de famille'}))

    class Meta:
        model = User
        fields = ("username", 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __int__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = "Nom d\'utilisateur"
        self.fields['username'].label = ''

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Mot de passe'
        self.fields['password1'].label = ''


        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirmer'
        self.fields['password2'].label = ''

# Create Add Record Form

class AddRecordForm(forms.ModelForm):
    first_name=forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder':'Prénom ',"class":'form-control'}), label="")
    last_name =forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder':'Nom ',"class":'form-control'}), label="")
    email=forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={'placeholder':'E-mail ',"class":'form-control'}), label="")
    phone=forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={'placeholder':'Téléphone ',"class":'form-control'}), label="")
    adress=forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={'placeholder':'Adresse ',"class":'form-control'}), label="")
    state=forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={'placeholder':'Pays ',"class":'form-control'}), label="")
    zipcode=forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={'placeholder':'Code Postal ',"class":'form-control'}), label="")

    class Meta:
        model=Record
        exclude=('user',)

website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import SignUpForm, AddRecordForm
from .models import Record
from team.models import Team


def site(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Authentifier l'utilisateur
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, " Tu es connectés.")
            return redirect('website:site')
        else:
            messages.success(request, "Erreur de connexion. Veuillez réessayer.")
            return redirect('website:site')
    return render(request, "site.html")

def records(request):
    records = Record.objects.all()
    if request.user.is_authenticated:
        return render(request, 'records.html', {"records":records})
    else:
        messages.success(request, "Vous devez d'abord vous connectez !")
        return redirect('site')

def factures(request):
    return render(request, "factures.html")


def logout_user(request):
    logout(request)
    messages.success(request, "Tu es déconnecté ...")
    return redirect("website:site")

def register_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # Authenticate and login
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            # Message success before redirect
            messages.success(request, 'Votre compte a été bien créé. Bienvenue chez vous !')

            team=Team.objects.create(name="Le nom de l'équipe", created_by=request.user)
            team.members.add(request.user)
            team.save()

            return redirect('website:site')
    else:
        form = SignUpForm()
    return render(request, 'register.html', {"form": form})


def customer_record(request, pk):
    if request.user.is_authenticated:
        # Look Up Records
        customer_record= Record.objects.get(id=pk)
        return render(request, 'record.html', {"customer_record":customer_record})
    else:
        messages.success(request, "Vous devez d'abord vous connectez !")
        return redirect('website:site')

def delete_record(request, pk):
    if request.user.is_authenticated:
        delete_it = Record.objects.get(id=pk)
        delete_it.delete()
        messages.success(request, "La personne a été bien supprimée de la liste...")
        return redirect( 'website:records')
    else:
        messages.success(request, "Vous devez d'abord vous connectez !")
        return redirect('website:site')


def add_record(request):
    form=AddRecordForm(request.POST or None)
    if request.user.is_authenticated:
        if request.method=="POST":
            if form.is_valid():
                add_record=form.save()
                messages.success(request, "Ajout réussit...")
                return redirect('website:records')
        return render(request, 'add_record.html', {'form':form})
    else:
        messages.success(request, "Vous devez d'abord vous connectez...")
        return redirect('website:site')


def update_record(request,pk):
    if request.user.is_authenticated:
        current_record = Record.objects.get(id=pk)
        form = AddRecordForm(request.POST or None, instance=current_record)
        if form.is_valid():
            form.save()
            messages.success(request, "Vous avez effectué des modifications...")
            return redirect('records')
        return render(request, 'update_record.html', {'form': form})
    else:
        messages.success(request, "Vous devez d'abord vous connectez...")
        return redirect('website:site')

@login_required
def my_account(request):
    team=Team.objects.filter(created_by=request.user).first()
    return render(request, 'myaccount.html', {'team':team})

website/templates/add_record.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-6 offset-md-3">
<h1> Ajouter </h1>
    <form method="POST" action="{% url 'website:add_record' %}">
        {% csrf_token %}
        {{ form.as_p }}




        <br>
        <button type="submit" class="btn btn-secondary">Ajouter client</button>
        <a href="{% url 'website:records' %}" class="btn btn-secondary">Retour</a>
    </form>

</div>





{% endblock %}

website/templates/base.html
<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body >
    {% include "navbar.html" %}
    <div class="container">
      <br>
    {% if messages %}

      {% for message in messages %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>

      {% endfor %}
    {% endif %}

      {% block content %}
      {% endblock %}
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>




  <footer class="footer bg-light fixed-bottom">
    <div class="container text-center">
        <p>&copy; 2023 Jamila - Tous droits réservés</p>
    </div>
  </footer>

  </body>
</html>

website/templates/home.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}

        <table class="table table-striped table-hover table-bordered">
          <thead class="table-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Téléphone</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Pays </th>
                    <th scope="col">Code postal</th>
                    <th scope="col">Date</th>

                </tr>
          </thead>
          <tbody>

            {% for record in records%}
            <tr>
                <td> <a href="{% url 'record' record.id %}" {{ record.id}}>{{ record.id}}</td>
                <td>{{ record.first_name}}
                {{ record.last_name}}</td>
                <td>{{ record.phone}}</td>
                <td>{{ record.email}}</td>
                <td>{{ record.adress}}</td>
                <td>{{ record.state}}</td>
                <td>{{ record.zipcode}}</td>
                <td>{{record.created_at}}</td>

            </tr>
            {% endfor %}


          </tbody>
        </table>

        {% else %}
        <div class="col-md-6 offset-md-3">
            <h1> Connexion </h1>
            <form method="POST" action="{% url 'home' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="text" class="form-control" name="username" placeholder="Nom d'utilisateur" required>
                </div>
                <br>
                <div class="mb-3">
                    <input type="password" class="form-control" name="password" placeholder="Mot de passe" required>
                </div>
                <br>
                <button type="submit" class="btn btn-secondary">Se connecter</button>
            </form>
        </div>

    {% endif %}
{% endblock %}

website/templates/myaccount.html
{% extends 'base.html' %}

{% block content %}

<div class="py-6 px-6">
    <h1 class="text-xl mb-1 text-center">Mon compte</h1>
    <p>
        <strong>Nom d'utilisateur:</strong> {{ request.user.username }}
    </p>
    <p>
        <strong>Equipe:</strong> {{ team.name }}

        {% if team.created_by == request.user %}
        <a href="{% url 'edit_team' team.id %}"> (Modifier) </a>
        {% endif %}
    </p>
    <hr class="mb-4">

    <a href="{% url 'website:logout' %}" class="btn btn-danger">Se déconnecter</a>

</div>
{% endblock %}

website/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'website:site' %}">Jamila</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'leads:leads_list' %}">Prospects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'client:clients_list' %}">Clients</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:site' %}">Se Connecter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:register' %}">Créer un compte</a>
          </li>
        {% endif %}
      </ul>



      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:myaccount' %}">Profil</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

website/templates/record.html
{% extends 'base.html' %}
{% block content %}

<div class="card" xmlns="http://www.w3.org/1999/html">
  <div class="card-header">
   <strong>{{ customer_record.first_name}} {{ customer_record.last_name}}</strong>
  </div>
  <div class="card-body">
    <p class="card-text">
        <strong> ID: </strong> {{ customer_record.id}}</p>
<p class="card-text">
        <strong> Téléphone: </strong>{{ customer_record.phone}}</p>
<p class="card-text">
        <strong> E-mail: </strong>{{ customer_record.email}}</p>
<p class="card-text">
        <strong> Adresse: </strong>{{ customer_record.adress}}</p>
<p class="card-text">
        <strong> Ville: </strong>{{ customer_record.state}}</p>
<p class="card-text">
        <strong> Code postale: </strong>{{ customer_record.zipcode}}</p>
<p class="card-text">
        <strong> Date: </strong>{{ customer_record.created_at}}</p>

  </div>
</div>
<br>
<a href="{% url 'website:records' %}" class="btn btn-secondary">Retour</a>

<a href="{% url 'website:delete_record' customer_record.id %}" class="btn btn-danger">Supprimer </a>

<a href="{% url 'website:update_record' customer_record.id %}" class="btn btn-success">Modifier</a>


{% endblock%}

website/templates/records.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <table class="table table-striped table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Téléphone</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Pays</th>
                    <th scope="col">Code postal</th>
                    <th scope="col">Date</th>
                </tr>
            </thead>
            <tbody>
                       {% for record in records %}
            <tr onclick="window.location='{% url 'website:record' record.id %}'">
                <td>{{ record.id }}</td>
                <td>{{ record.first_name }} {{ record.last_name }}</td>
                <td>{{ record.phone }}</td>
                <td>{{ record.email }}</td>
                <td>{{ record.address }}</td>
                <td>{{ record.state }}</td>
                <td>{{ record.zipcode }}</td>
                <td>{{ record.created_at }}</td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
        <a href="{% url 'website:add_record' %}" class="btn btn-primary">Ajouter un client</a>
        <hr>
        <a href="{% url 'website:site' %}" class="btn btn-secondary">Retour</a>
    {% else %}
        <div class="col-md-6 offset-md-3">
            <h1>Connexion</h1>
            <form method="POST" action="{% url 'website:site' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="text" class="form-control" name="username" placeholder="Nom d'utilisateur" required>
                </div>
                <br>
                <div class="mb-3">
                    <input type="password" class="form-control" name="password" placeholder="Mot de passe" required>
                </div>
                <br>
                <button type="submit" class="btn btn-secondary">Se connecter</button>
            </form>
        </div>
    {% endif %}
{% endblock %}

website/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container ">
    <div class="col-md-6 offset-md-3 border p-4 bg-white">
        <h1 class="text-center text-muted fw-bold ">Jamila</h1>
        <p class="text-center custom-heading"> Inscrivez-vous pour accéder aux fonctionnalités qu'offre Jamila</p>
        <form method="POST" action="">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    {% if field.name == 'username' %}
                        <label for="{{ field.id_for_label }}"></label>
                        <input type="text" name="{{ field.name }}" class="form-control" placeholder="{{ field.label }}" required>
                    {% elif field.name == 'password1' %}
                        <label for="{{ field.id_for_label }}">Mot de passe</label>
                        <input type="password" name="{{ field.name }}" class="form-control" required>
                    {% elif field.name == 'password2' %}
                        <label for="{{ field.id_for_label }}">Confirmation du mot de passe</label>
                        <input type="password" name="{{ field.name }}" class="form-control" required>
                    {% else %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    {% endif %}
                    {% if field.errors %}
                        <div class="text-danger">
                            {% for error in field.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">S'inscrire</button>
            <br>
            <p>Vous avez un compte? <a href="{% url 'website:site'%}">Connectez-vous</a> </p>
        </form>
    </div>
</div>
{% endblock %}

website/templates/site.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}

    <div class="container">
        <div class="row" >
            <div class="col-md-3 mb-4">
                <a href="{% url 'website:records'%}" class="text-decoration-none">
                    <div class="bg-white rounded shadow-sm p-4">
                        <h3 class="font-weight-bold text-dark text-center">CRM</h3>
                        <p class="text-center text-dark">Les informations client</p>
                        <button class="btn btn-success">Accéder</button>
                    </div>
                </a>
            </div>

            <div class="col-md-3 mb-4">
                <a href="{% url 'facturation:factures'%}" class="text-decoration-none">
                    <div class="bg-white rounded shadow-sm p-4">
                        <h3 class="font-weight-bold text-dark text-center">Mes factures</h3>
                        <p class="text-center text-dark">Liste des factures</p>
                        <button class="btn btn-success">Accéder</button>
                    </div>
                </a>
            </div>

            <div class="col-md-3 mb-4">
                <a href="{% url 'todo:todo_list'%}" class="text-decoration-none">
                    <div class="bg-white rounded shadow-sm p-4">
                        <h3 class="font-weight-bold text-dark text-center">To do</h3>
                        <p class="text-center text-dark">Tâches à réaliser</p>
                        <button class="btn btn-success">Accéder</button>
                    </div>
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 mb-4">
                <a href="{% url 'leads:leads_list'%}" class="text-decoration-none">
                    <div class="bg-white rounded shadow-sm p-4">
                        <h3 class="font-weight-bold text-dark text-center">Prospects</h3>
                        <p class="text-center text-dark">Potentiels clients</p>
                        <button class="btn btn-success">Accéder</button>
                    </div>
                </a>
            </div>

            <div class="col-md-3 mb-4">
                <a href="{% url 'client:clients_list'%}" class="text-decoration-none">
                    <div class="bg-white rounded shadow-sm p-4">
                        <h3 class="font-weight-bold text-dark text-center">Clients</h3>
                        <p class="text-center text-dark">Les clients existants</p>
                        <button class="btn btn-success">Accéder</button>
                    </div>
                </a>
            </div>

            <div class="col-md-3 mb-4">
                <a href="{% url 'dashboard:dashboard'%}" class="text-decoration-none">
                    <div class="bg-white rounded shadow-sm p-4">
                        <h3 class="font-weight-bold text-dark text-center">Dashboard</h3>
                        <p class="text-center text-dark">Prospects et Clients récents</p>
                        <button class="btn btn-success">Accéder</button>
                    </div>
                </a>
            </div>


        </div>
    </div>



    {% else %}
    <div class="container bg-white">
        <div class="col-md-6 offset-md-3 border p-3 ">
            <h1 class="text-center"> Jamila </h1>
            <form method="POST" action="{% url 'website:site' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="text" class="form-control" name="username" placeholder="Nom d'utilisateur" required>
                </div>
                <br>
                <div class="mb-3">
                    <input type="password" class="form-control" name="password" placeholder="Mot de passe" required>
                </div>
                <button type="submit" class="btn btn-primary">Se connecter</button>
                <br>

            </form>
            <br>
            <p>Vous n'avez pas de compte? <a href="{% url 'website:register'%}">Inscrivez-vous</a> </p>
        </div>
    </div>
    {% endif %}
{% endblock %}

website/templates/update_record.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-6 offset-md-3">
<h1> Modification </h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <br>
        <button type="submit" class="btn btn-secondary">Modifier</button>
    </form>

</div>





{% endblock %}