client/urls.py
from django.urls import path
from . import views

app_name = 'client'
urlpatterns=[

    path("", views.clients_list, name="clients_list"),
    path("<int:pk>/", views.clients_detail, name="clients_detail"),
    path("<int:pk>/delete/", views.clients_delete, name="clients_delete"),
    path("<int:pk>/edit/", views.clients_edit, name="clients_edit"),
    path("add/", views.clients_add, name="clients_add"),

    ]

crm/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('website/', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('facturation/', include('facturation.urls')),
    path('team/', include('team.urls')),
    path('todo/', include('todo.urls')),
    path('leads/', include('leads.urls')),
    path('client/', include('client.urls')),

]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns=[
    path("", views.dashboard, name="dashboard"),
]

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'
urlpatterns=[

    path("", views.leads_list, name="leads_list"),
    path("<int:pk>/", views.leads_detail, name="leads_detail"),
    path('<int:pk>/delete/', views.leads_delete, name='leads_delete'),
    path("add_lead/", views.add_lead, name="add_lead"),
    path("<int:pk>/convert", views.convert_to_client, name="leads_convert"),
    path('<int:pk>/edit/', views.leads_edit, name="leads_edit"),

]

dashboard/models.py
from django.db import models

# Create your models here.

leads/models.py
from django.db import models
from django.contrib.auth.models import User
from team.models import Team

class Lead(models.Model):
    LOW = "faible"
    MEDIUM = "moyenne"
    HIGH = "forte"

    CHOICES_PRIORITY = (
        (LOW, "faible"),
        (MEDIUM, "moyenne"),
        (HIGH, "forte"),
    )

    NEW = 'nouveau'
    CONTACTED = 'contacté'
    WON = 'gagné'
    LOST = 'perdu'

    CHOICES_STATUS = (
        (NEW, 'nouveau'),
        (CONTACTED, 'contacté'),
        (WON, 'gagné'),
        (LOST, 'perdu'),
    )
    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client=models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering= ('name',)

    def __str__(self):
        return self.name

dashboard/views.py
from django.shortcuts import render
from leads.models import Lead
from client.models import Client

def dashboard(request):
    leads = Lead.objects.filter(created_by=request.user).order_by('-created_at')[:5]
    clients = Client.objects.filter(created_by=request.user).order_by('-created_at')[:5]

    context = {
        'leads': leads,
        'clients': clients,
    }

    return render(request, 'dashboard.html', context)

dashboard/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="py-6 px-6">
    <h1 class="text-xl mb-1 text-center">Dashboard</h1>
    <div class="row">
        <div class="col-md-6 bg-light leads-column mb-4">
            <h4 class="mb-3 text-lg">Plus récents prospects</h4>
            <hr>
            {% for lead in leads %}
            <div class="mb-2 lead">
                <h3 class="font-weight-bold" style="font-size: 14px;" >{{ lead.name }}</h3>
                <p class="text-muted" style="font-size: 14px;">Statut: {{ lead.get_status_display }}</p>
                <p class="text-muted" style="font-size: 14px;">Priorité: {{ lead.get_priority_display }}</p>
                <a href="{% url 'leads:leads_detail' lead.pk %}" style="font-size: 14px;">Voir plus</a>
            </div>
            <hr>
            {% endfor %}
        </div>

        <div class="col-md-6 px-4 py-6 bg-light rounded-xl clients-column">
            <h4 class="mb-1 text-lg">Plus récents clients</h4>
            <hr>
            {% for client in clients %}
            <div class="mb-6 client">
                <h3 class="font-weight-bold" style="font-size: 14px;">{{ client.name }}</h3>
                <a href="{% url 'client:clients_detail' client.pk %}" style="font-size: 14px;">Voir plus</a>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}